---
title: GTFS2EMIS an R package to estimate public transport emissions based on GTFS data 
journal: "`r rticles::copernicus_journal_abbreviations(journal_name = 'communication')`"
author:
  - given_name: Rafael
    surname: H.M. Pereira
    affiliation: "1, *"
    email: rafael.pereira@ipea.gov.br
  - given_name: Pedro
    surname: R. Andrade
    email: pedro.andrade@inpe.br
    affiliation: 2
  - given_name: Joao Pedro
    surname: Bazzo 
    affiliation: "1, *"
    email: joao.bazzo@gmail.com
    corresponding: true
# If you have more than one corresponding author, add them manually using the following structure (note the commas):
# Two authors: Daniel Nüst (daniel.nuest@uni-muenster.de) and Josiah Carberry (j.carberry@orcid.org)
# Three authors or more: Daniel Nüst (daniel.nuest@uni-muenster.de), Josiah Carberry (j.carberry@orcid.org), and Markus Konkol (m.konkol@wwu.de)
# If the following line is uncommented, the "corresponding: true" above are ignored
#correspongdingauthors: Daniel Nüst (daniel.nuest@uni-muenster.de) and Josiah Carberry (j.carberry@orcid.org)
# If an author is deceased, please mark the respective author name(s) with a dagger '†' and add a further affiliation; put the decease date in the 'address' field", see 'Nikolaus Copernicus' in template.
# If authors contributed equally, please mark the respective author names with an asterisk '*' and add a further affiliation: 'These authors contributed equally to this work.'", see template.
affiliation:
  - code: 1
    address: Institute for Applied Economic Research, Brasília, Brazil
  - code: 2
    address: National Institute of Space Research, São José dos Campos, Brazil
abstract: |
  The abstract goes here.
  It can also be on _multiple lines_.
bibliography: global-pt-emission.bib
running:
  title: R Markdown Template for Copernicus
  author: Nüst et al.
# This section is mandatory even if you declare that no competing interests are present.
competinginterests: |
  The authors declare no competing interests.
# See https://publications.copernicus.org/for_authors/licence_and_copyright.html, normally used for transferring the copyright, if needed. 
# Note: additional copyright statements for affiliated software or data need to be placed in the data availability section. 
copyrightstatement: |
  The author's copyright for this publication is transferred to institution/company. 
### The following commands are for the statements about the availability of data sets and/or software code corresponding to the manuscript.
### It is strongly recommended to make use of these sections in case data sets and/or software code have been part of your research the article is based on.
### Note: unless stated otherwise, software and data affiliated with the manuscript are assumed to be published under the same licence as the article (currently Creative Commons 4.0)
availability:
  #code: |
  #  use this to add a statement when having only software code available
  #data: |
  #  use this to add a statement when having only data sets available
  codedata: |
    use this to add a statement when having data sets and software code available
  sample: |
    use this section when having geoscientific samples available
videosupplement: |
  use this section when having video supplements available
authorcontribution: |
  Daniel wrote the package. Josiah thought about poterry. Markus filled in for a second author.
disclaimer: |
  We like Copernicus.
acknowledgements: |
  Thanks to the rticles contributors!
appendix: |
  \section{Figures and tables in appendices}
  Regarding figures and tables in appendices, the following two options are possible depending on your general handling of figures and tables in the manuscript environment:
  \subsection{Option 1}
  If you sorted all figures and tables into the sections of the text, please also sort the appendix figures and appendix tables into the respective appendix sections.
  They will be correctly named automatically.
  \subsection{Option 2}
  If you put all figures after the reference list, please insert appendix tables and figures after the normal tables and figures.
  
  To rename them correctly to A1, A2, etc., please add the following commands in front of them:
  `\appendixfigures` needs to be added in front of appendix figures
  `\appendixtables` needs to be added in front of appendix tables
  
  Please add `\clearpage` between each table and/or figure. Further guidelines on figures and tables can be found below.
output:
  rticles::copernicus_article: 
    citation_package: natbib
    highlight: NULL
    keep_tex: true
  bookdown::pdf_book:
    citation_package: biblatex
    base_format: rticles::copernicus_article # for using bookdown features like \@ref()
---

# Introduction

Transport emissions have been widely recognized among the leading and growing contributors to global emissions [@caiazzo_air_2013; @nocera_assessing_2018 ]. There is also scant evidence of how transportation activities impact air quality in cities [@landrigan_lancet_2018], aggravating the negative short- and long-term effects pollution has on children premature deaths [@currie_traffic_2009], cardiovascular diseases [@brook_particulate_2010; @turner_long-term_2016], ischemic stroke [@wellenius_ambient_2012] and cognitive development [@chen_living_2017; @fu_association_2019; @shehab_effects_2019; @zhang_impact_2018]. This has a higher impact in low and middle-income countries [@combes_fine_2019], especially in more vulnerable groups, such as elderly people [@yap_particulate_2019] and children [@braga_health_2001; @gauderman_association_2015].
Understanding the spatial and temporal patterns of emissions is a key factor to adopt more precise public policies to reduce air pollution exposure [@clark_national_2014; @targino_spatial_2018], improve the housing and land use planning, and subsidize public investments  Particularly with public transport policies, extensive efforts have been made to quantify air pollution patterns and to understand the impact of  fleet technology, fuel, topography, and route choices on overall levels of air pollution (refs).

Most of the studies on public transportation emissions focus on emissions monitoring with remote sensing devices (refs), onboard diagnosis using PEMS (refs), vehicle counts data (refs), radar equipments (refs), public transport GPS data (refs), and fuel based estimates (top down approaches).  However, due to a restriction of spatial application, or costly local data collection, some of these approaches might not be easy to scale for other cities. Other approaches, such as air quality analysis (refs), satellite data observations (refs) would represent the final state of air quality but ultimately do not look only at bus emissions. Studies that identify and map pollution in low and middle-income countries are still needed, particularly when easily reproduced.

Our analysis contributes to the public transport emission literature by developing a novel methodology that leverages a widespread open data format for public transport networks known as General Transit Feed Specification (GTFS) to estimate vehicle emissions in a high spatial and temporal resolution. The method is presented in a R package “gtfs2emis” to allow friendly and reproducible use for different applications. In this paper, we present estimates on CO2, NOx, PM10, CO, CH4 hot exhaust emissions for 24 cities in the world, considering a typical business day on October 2019 --- as a baseline date. A comparison of the vehicle emissions rates of those transport networks is also presented, along with a discussion on the versatility and limitations of the method. 

The remainder of this paper is organized as follows. Section two presents a brief literature review on public transportation emissions. Section three describes the data and methods for the public transport data, emission factors databases and vehicle emissions estimates.. Section four presents the results, looking at the overall levels of pollutant emissions and its spatial and temporal resolution behavior. Finally, section five presents the final remarks and discusses some environmental insights that can be drawn from the package.



# Methods
## Transport model

### GTFS data

The method used in the paper leverages a global standard format for public transport data known as General Transit Feed Specification (GTFS). The GTFS data of a given public transport system is collected in a ZIP file, that brings detailed geolocated information on scheduled services including its stops, routes, trips, stop times and calendar organized in a structured text file.

This format was originally created in the mid-2000s by Google and Portland transport authority and it has since then become adopted worldwide by more than 600 cities [@noauthor_openmobilitydata_nodate]. The simplicity of this data format and its wide adoption creates a common ground for researchers and practitioners across the globe to develop and share computational methods that can be seamlessly deployed across multiple cities to manage fleet allocation, plan transport services, etc. Detailed aspects of the GTFS contents are found in [@noauthor_reference_nodate].

We expand the sample of cities with GTFS data collected directly from local transport authorities and from Transit Feed archives - the largest GTFS open data repository website. The GTFS data were pre-processed to filter by bus routes and to check consistencies on the required files (e.g. agency, stops, routes, trips, stop times). The months of October and November 2019 are used as the baseline date for the emissions estimates, in order to avoid possible differences in public transportation schedules due to the COVID-19 pandemic. A summary of the main GTFS information is described in Table 1, together with the fleet data.

## GTFS2gps

The process to convert GTFS files to GPS-like spatial data points is done for every trip of the schedule. It interpolates the space-time position of each vehicle in each trip considering the network distance and average speed between stops. It samples the timestamp of each vehicle every 50m.

[//]: # are we mentioning something about the interpolation?--------------------

Once a GPS data format is generated from GTFS, a few adjustments on speed is made. Since the mean speed is estimated in a street link between two bus stops (e.g. stop “i” and “i+1”), the data on departure time of “i” and arrival time of “i+1” is necessary. If “i+1” arrival time is very close or the same as the departure time of “i”, the speed will be very high (>100 kph) or infinite. In such cases, we consider the speed to be the mean speed of all the trips in this specific bus route. Therefore, the departure times of the GPS are recalculated based on the new travelled speeds. This adjustment is also necessary in street links without valid arrival or departure times: before the first bus stop of the route (where only arrival time is available); after the last bus stop (only departure time is available); and trips with invalid stop times. 


## Emission model
### Emission factors

Emission factors (EFs) are empirical functional relations between pollutant emissions and the activity that causes them (Franco et al., 2013). This study uses EF based on Environmental Sanitation Technology Company (CETESB) --- for Brazil; California Air Resources Board (CARB) --- for the California U.S; Motor Vehicle Emission Model (MOVES) for regions in U.S. outside California; European Environment Agency (EEA) --- for European countries. Among these sources, EMFAC, MOVES and EMEP/EEA have speed-dependent emission factors. 
For the Brazilian cities’ estimates, the local EF is scaled to the EMEP/EEA function considering the average speed of the vehicle driving cycle. The brazilian emission factor is related to speed by the expression

\begin{equation}
EF^{scaled}_{i,j,k,l}=EF^{local}_{i,j,k,l}\frac{EF(V_i)_{j,k,l}}{EF(V_{dc})_{j,k,l}}.  
\end{equation}

where $EF_{i,j,k,l}^{scaled}$ is the scaled emission factors for each street link $i$, bus type $j$, fuel $k$, age $l$,; $EF_{i,j,k,l}^{local}$ is the local emission factor; $EF(V_i)_{j,k,m}$ and $EF(V_{dc})_{j,k,l}$ is the EEA emission factor at the speed of $V_i$;and the driving cycle $V_{dc}$ of FTP-25 (33 kph).

The CARB’s (California Air Resources Board) EMFAC (EMission FACtor) model estimates statewide and regional emissions inventory by multiplying emissions rates with vehicle activity data. The running exhaust emission factors are distributed according to speed bins from 5 to 90, with 5 mph incremental. It allows modeling one season (summer, winter or annual average) due to temporal variations of EF due to meteorological conditions (temperature and relative humidity); and geographic area (Statewide, Air Basin, Air District, Metropolitan Planning Organization, Country and Sub-Area). Detailed data on emission factors are found in @noauthor_emfac_nodate. 

\begin{table*}[t]
\caption{Emission factor sources, related bus categories and variables associated.}
\begin{tabular}{ccc}
\hline
Source & Buses categories & Variables \\ \hline
CETESB & Micro, Standard, Articulated & Age, Fuel, EURO stage \\
EMFAC model & Urban Buses & Age, Fuel \\
EMEP/EEA & Micro, Standard, Articulated & Fuel, EURO stage, technology, load, slope \\
MOVES U.S EPA & Urban Buses & Age, Fuel \\
\hline
\end{tabular}
\belowtable{Table footnotes}
\end{table*}

\begin{table*}[t]
\caption{Association between model year, PROCONVE Norm and EURO stage for the brazilian fleet (adapted from ICCT).}
\begin{tabular}{ccc}
\hline
PROCONVE Norm & EURO equivalent & Year range \\ \hline
P4  & II  & 1998 - 2003 \\
P5  & III  & 2004 - 2011 \\
P8  & V & 2012 - 2019\\
\hline
\end{tabular}
\belowtable{Table footnotes}
\end{table*}


\begin{table*}[t]
\caption{Summary of all vehicle classes covered by the Tier 2 methodology}
\begin{tabular}{ccc}
\hline
Urban bus category  & Euro Stage  \\ \hline
Urban CNG buses & Euro I, Euro II, Euro III, EEV   \\
Urban buses   &  Conventional, Euro I - Euro VI\\
Urban Diesel Hybrid  & Euro VI  \\
Urban biodiesel buses   & Conventional, Euro I - Euro VI\\
\hline
\end{tabular}
\belowtable{Table footnotes}
\end{table*}


European exhaust emission factors are presented in the EMEP/EEA air pollutant inventory guidebook, considering the COPERT 5.4 Software version. This study considered average load on all trips and zero slope rate for all studied cities. Urban Buses are presented in three main categories, which are Urban Buses Midi (<= 15 t), Standard (15 - 18 t), Articulated (>18 t), Urban Diesel Buses Hybrid, CNG (Compressed Natural Gas) Buses. The speed dependent emissions factors for diesel urban buses have been taken from HBEFA (Handbook Emission Factors for Road Transport), for Euro I to Euro VI emissions standards. Distinct parameters of EF were considered for Euro V standard, according to the control technology, that can be Exhaust Gas Recirculation —  EGR or Selective Catalytic Reduction — SCR. According to EMEP/EEA, it is estimated that 75% of Euro V heavy-duty vehicles are equipped with SCR. For the category of CNG buses, it has an additional emission standard known as Enhanced Environmental Vehicles (EEV), since it may have different combustion, after-treatment technology, and are associated with lower PM and NOx emission rates compared with diesel buses (add source). Only older CNG buses are classified in EURO I, II, or III. Detailed aspects of hot exhaust emissions rates of Europe are found in the EMEP/EEA guidebook.

### Emission estimates


The estimates of hot exhaust emissions for each trip is given by

\begin{equation}
EH_{i,j,k,l} = L_i\times EF_{i,j,k,l}
\end{equation}

where $EH_{i,j,k,l}$ is the emission for the street link $i$, vehicle category $j$, fuel $k$ and age $l$; $L_i$ is the length of the street link $i$(km); $EF_{i,j,k,l}$ is the emission factor (g/km). In order to evaluate emissions spatially, the overall emissions are allocated into a 350m resolution grid (H3 resolution from Uber). 


### Emission post-processing

Subsubsection text here. 

# Estimate Curitiba's emissions using GTFS2emis model
## Traffic data for Curitiba
## Emission factors
## Emission estimates


\conclusions[Discussions and Conclusions]
