#' @title Emissions post-processsing 
#'
#' @description Aggregate emissions generated by emis function by time, 
#' vehicle type and segment link (spatial)
#'
#' @param emi List; Emissions (in units 'g') generated by function emis
#' @param veh Character; Vehicle type displayed in 'names(emi)', 'all' 
#'  (full aggregation by 'vehicle_type'), or 'none' Missing input the emissions are not aggregated.
#' @param time Character; Emission can be aggregated into 'hour' and'hour-minute'. 
#'  Missing input (Default) no aggregation without considering time consideration.
#' @param time_dt Vector; Vector containing 'departure_time'. 
#'  Only used when 'hour' or 'hour-minute' is selected. 
#' @return Units (in g); emissions
#' @export
emis_post <- function(emi,veh,time,time_dt){
  #  emi <- units::set_units(2,"g")
  #  veh <- "all"
  #  time <- "hour"
  # time_dt <- "12:40:00"
  # emi filter
  if(missing(emi)) stop("'emi' parameter is missing, without default")
  if(class(emi) == "units" && is.null(dim(emi))){
    emi <- data.table::as.data.table(emi)
  }
  # vehicle category - filter
  if(missing(veh) == FALSE){
    if(veh == "all"){
      temp_emi <- sapply(1:ncol(emi), function(i){emi[,i]}) %>% rowSums()
      emi <- data.table::data.table("all" = temp_emi)
    }else{
      emi <- emi[,veh]
    }
  }
  # time - filter
  if(missing(time) == FALSE){
    if(missing(time_dt)){stop("Please provide 'time_dt' data.")}
    dtt <- data.table::data.table("time" = time_dt) # "12:30:05"
    lapply(1:ncol(emi), function(i){ # i =1
      dtt[,names(emi)[i] := emi[[i]]]
    })
    if(time == "hour"){
      dtt[,time := data.table::hour(data.table::as.ITime(time))][order(time),]
      dtt <- dtt[ , lapply(.SD, sum), .SDcols = !"time", by = "time"]
    }
    if(time == "hour-minute"){
      dtt[,time := paste0(data.table::hour(data.table::as.ITime(time)),":",
                          data.table::minute(data.table::as.ITime(time)))][order(time),]
      dtt <- dtt[ , lapply(.SD, sum), .SDcols = !"time", by = "time"]
    }
    return(dtt)
  }else{
    dtt <- data.table::data.table(emi)
    return(dtt)
  }
}
