#' @title Emissions post-processing 
#'
#' @description Aggregate emissions generated by emis function by time, 
#' vehicle type and segment link (spatial).
#'
#' @param data data.table; Data.table with emissions and departure_time data.
#' @param emi character; Columns names of emissions information.
#' @param time_class character; Emissions can be aggregated by 'hour' or 'hour-minute'.
#' @param time_column vector; Vector containing 'departure_time'. 
#'  Only used when 'hour' or 'hour-minute' is selected. 
#' @return units ('g'); emissions.
#' @export
#' @examples 
#' require(magrittr)
#' data <- gtfs2gps::read_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps")) %>%
#'   gtfs2gps::filter_by_shape_id("51982") %>%
#'   gtfs2gps::gtfs2gps() %>%
#'   gtfs2gps::gps_as_sflinestring() %>%
#'   dplyr::select(trip_id, speed, dist, departure_time)
#' 
#' data$dist <- units::set_units(data$dist, "km")
#' 
#' total_fleet <- data.table::data.table(year = c(2005, 2010:2012, 2014, 2015, 2017:2019),
#'                                       bus = c(1, 61, 50, 1, 45, 18, 62, 27, 31),
#'                                       veh_type_euro = "Urban Buses Standard 15 - 18 t",
#'                                       euro_stage = c("II", "IV", "IV", rep("V", 6)))
#' total_fleet$fleet_composition = total_fleet$bus/sum(total_fleet$bus)
#' 
#' EF_usa <-  gtfs2emis::ef_usa(pollutant = c("CO", "PM10"),
#'                  calendar_year = "2019",
#'                  model_year = total_fleet$year,
#'                  speed = vein::Speed(data$speed),
#'                  fuel = "Diesel")
#' emi_usa <- gtfs2emis::emis(fleet_composition = total_fleet$fleet_composition,
#'                            dist = data$dist, ef = EF_usa, prefix = "USA")
#' data <- cbind(data, emi_usa)
#' 
#' emi_post_usa <- gtfs2emis::emis_post(data = data, time_class = "hour",
#'                                      emi = c("USA_CO_total", "USA_PM10_total"),
#'                                       time_column = "departure_time")
emis_post <- function(data, emi, time_class, time_column = 'departure_time'){
  # 
  # check input consistency----
  
  data <- data.table::setDT(data)

  if(time_column %nin% colnames(data)){
    stop(paste0("'", time_column, "' is missing in the 'data'."))
  }

  # check emis class
  
  lapply(seq_along(emi), function(i){ # i = 1
    temp_emi <- data[, .SD, .SDcols = emi[i]]
    if(class(temp_emi[[1]]) != "units"){
      stop("emi neeeds to has class 'units'. Please, check package 'units'")
    }
    if(units(temp_emi[[1]])$numerator != "g" & units(temp_emi[[1]])$numerator != "kg"){
      stop("emi needs to has 'units' in 'g' or 'kg'.")
    }
  })
  
  #
  # agreggate by TIME
  #
  
  # time - filter
  temp_data <- data[, .SD, .SDcols = c(emi, time_column)]
  temp_data[, (time_column) := data.table::as.ITime(get(time_column))]
  temp_data <- temp_data[order(get(time_column)), ]
  
  if(missing(time_column) == FALSE){
    # 'hour' time stamp
    
    if(time_class == "hour"){
      temp_data[, (time_column) := data.table::hour(get(time_column))]
    }
    
    # 'hour-minute' time stamp
    
    if(time_class == "hour-minute"){
      temp_data[, (time_column) := paste0(data.table::hour(get(time_column)), ":",
                          data.table::minute(get(time_column)))]
    }
    
    # aggregate emissions and rename
    
    temp_data <- temp_data[, lapply(.SD, sum), .SDcols = !(time_column),
                           by = .("time" = get(time_column))]
    data.table::setnames(temp_data, "time", time_column)
  }

  return(temp_data)
}
