#' @title 
#' Emissions summary by aggregating results 
#'
#' @description 
#' Aggregate emissions generated by the \code{\link{emis}} function by time, 
#' vehicle type and segment link (spatial).
#'
#' @param emi_list data.table; Data.table with emissions and departure_time data.
#' @param emi_vars character; Columns names of emissions information.
#' @param by character; Emissions can be aggregated by 'time', 'age', 'veh_type' and 'pollutant'
#' @param time_column vector; Vector containing time_column. 
#' @param veh_vars vector; Vector containing variables of vehicle type.
#' @param pol_vars vector; Vector containing variables of pollutant. 
#'  Only used when 'hour' or 'hour-minute' is selected. 
#'  
#' @return units ('g'); emissions.
#' @export
#' 
#' @examples 
#' set.seed(1335)
#' dist = units::set_units(rnorm(100,0.250,0.03),"km")
#' ef <- ef_emep_europe(speed = units::set_units(rnorm(100,50,5),"km/h"),
#'                 veh_type = c("Ubus Std 15 - 18 t","Ubus Artic >18 t"),
#'                 euro = c("IV","V"),
#'                 pollutant = c("CO2","NOx"),
#'                 fuel = "D" ,
#'                 tech =  c("SCR","EGR"),
#'                 slope = 0.0,
#'                 load = 0.5,
#'                 fcorr = 1,
#'                 as_list = TRUE)
#' 
#' emi <- emis(fleet_composition =  c(0.7,0.3),
#'             dist = dist,
#'             ef = ef,
#'             aggregate = FALSE,
#'             as_list = TRUE)  
#' 
#' emi$time_column <- data.table::as.ITime(seq(1,14400,length.out = 100))
#
#' my_emis_summary <- emis_summary(emi_list = emi,
#'                      emi_var = "emi", 
#'                      by = "time",  # veh_type, time, pollutant 
#'                      time_column = "time_column",
#'                      veh_var = "veh_type", # veh_type
#'                      pol_var = "pollutant") # pollutant
emis_summary <- function(emi_list, emi_vars, by, time_column = NULL, pol_vars = NULL, veh_vars = NULL){
  
  #
  # check list condition -----
  #
  
  if(class(emi_list) != "list"){
    stop("'emi_list' input needs to have a list format.")
  }
  
  #
  # check consistencies----
  #
  
  if(by != "time" & by != "pollutant"  & by != "veh_type"){
    stop("'by' argument needs to be 'time', 'veh_type' or 'pollutant' type")
  }
  if(by == "time"){
    if(missing(time_column)){
      stop("'time_column' argument is required when by = 'time' is assigned")
    }
    if(length(emi_list[[time_column]]) != nrow(emi_list[[emi_vars]])){
      stop("'emi_vars' columns needs to have the same length of 'time_column'")
    }
    if(missing(emi_vars) | missing(pol_vars)){
      stop("'emi_vars' or 'pol_vars' are missing for 'time' post processing")
    }
  }
  if(by == "pollutant"){
    if(missing(pol_vars)){
      stop("pol_vars are missing for 'pollutant' post processing")
    }
  }
  if(by == "veh_type"){
    if(missing(veh_vars) | missing(pol_vars)){
      stop("pol_vars are missing for 'pollutant' post processing")
    }
  }
  
  #
  # check 'emi_vars' units-----
  #
  
  lapply(seq_along(emi_list[[emi_vars]]),function(i){
    if(class(emi_list[[emi_vars]][[i]]) != "units"){
      stop("emi neeeds to has class 'units'. Please, check package 'units'")
    }
    if(units(emi_list[[emi_vars]][[i]])$numerator != "g" & units(emi_list[[emi_vars]][[i]])$numerator != "kg"){
      stop("emi needs to has 'units' in 'g' or 'kg'.")
    }
  })
  
  #
  # get units-----
  #
  
  myunits <- sapply(seq_along(emi_list[[emi_vars]]),function(i){
    units::deparse_unit(emi_list[[emi_vars]][[i]])
  }) %>% unique()
  
  #
  # aggregate by TIME------
  #
  
  if(by == "time"){
    
    tmp_dt <- data.table::copy(emi_list[[emi_vars]])
    # time - filter
    emi_list[[time_column]] <- data.table::hour(emi_list[[time_column]])
    
    tmp_dt <- emi_to_dt(emi_list = emi_list
                        ,emi_vars = emi_vars
                        ,veh_vars = veh_vars
                        ,pol_vars = pol_vars
                        ,segment_vars = time_column)
    tmp_dt <- tmp_dt[,lapply(.SD,sum,na.rm = TRUE)
                     ,by = c(time_column,pol_vars)
                     ,.SDcols = c(emi_vars)]
    
  }
  
  #
  # aggregate by 'veh_type' -----------
  #
  if(by == "veh_type"){
    
    tmp_dt <- data.table::copy(emi_list[[emi_vars]])
    tmp_dt <- emi_to_dt(emi_list = emi_list
                        ,emi_vars = emi_vars
                        ,veh_vars = veh_vars
                        ,pol_vars = pol_vars)
    tmp_dt <- tmp_dt[,lapply(.SD,sum,na.rm = TRUE)
                     ,by = c(veh_vars,pol_vars)
                     ,.SDcols = c(emi_vars)]
  }
  
  #
  #  aggregate by 'pollutant' --------
  #
  if(by == "pollutant"){
    
    tmp_dt <- data.table::copy(emi_list[[emi_vars]])
    tmp_dt <- emi_to_dt(emi_list = emi_list
                        ,emi_vars = emi_vars
                        ,veh_vars = veh_vars
                        ,pol_vars = pol_vars)
    tmp_dt <- tmp_dt[,lapply(.SD,sum,na.rm = TRUE)
                     ,by = c(pol_vars)
                     ,.SDcols = c(emi_vars)]
    
  }
  
  return(tmp_dt)
}
