#' @title Emissions post-processsing 
#'
#' @description Aggregate emissions generated by emis function by time, 
#' vehicle type and segment link (spatial)
#'
#' @param emi List; Emissions (in units 'g') generated by function emis
#' @param veh Character; Vehicle type displayed in 'names(emi)', 'all' 
#'  (full aggregation by 'vehicle_type'), or 'none' Missing input the emissions are not aggregated.
#' @param time Character; Emission can be aggregated into 'hour' and'hour-minute'. 
#'  Missing input (Default) no aggregation without considering time consideration.
#' @param time_dt Vector; Vector containing 'departure_time'. 
#'  Only used when 'hour' or 'hour-minute' is selected. 
#' @return Units (in g); emissions
#' @examples 
#' set.seed(12039)
#' temp_emi <- emis(veh = data.table::data.table("veh1" = 0.75,"veh2" = 0.25), # sum(veh) = 1
#'                  dist = units::set_units(rnorm(10,mean = 8),'km'),
#'                  ef = list("veh1" = units::set_units(rnorm(10,0.35,0.01),'g/km'),
#'                            "veh2" = units::set_units(rnorm(10,0.27,0.01),'g/km')))
#' temp_time <- c("10:40","10:40","10:42","10:44","10:45",
#'                "10:46","10:47","10:48","10:49","10:50")
#' 
#' emis_post(emi = temp_emi,veh = 'all',time = 'hour',time_dt = temp_time)
#' emis_post(emi = temp_emi,veh = 'all',time = 'hour-minute',time_dt = temp_time)
#' emis_post(emi = temp_emi,veh = 'veh1',time = 'hour-minute',time_dt = temp_time)
#' emis_post(emi = temp_emi,time = 'hour',time_dt = temp_time)
#' emis_post(emi = temp_emi,veh = 'veh1')
#' emis_post(emi = temp_emi)
#' @export
emis_post <- function(emi,veh,time,time_dt){
  # emi filter
  if(missing(emi)) stop("'emi' parameter is missing, without default")
  # vehicle category - filter
  if(missing(veh) == FALSE){
    if(veh == "all"){
      temp_emi <- sapply(seq_along(emi), function(i){emi[[i]]}) %>% rowSums()
      emi <- list("all" = matrix(temp_emi))
    }else{
      emi <- emi[veh]
    }
  }
  # time - filter
  if(missing(time) == FALSE){
    if(missing(time_dt)){stop("Please provide 'time_dt' data.")}
    dtt <- data.table::data.table("time" = time_dt) # "12:30:05"
    lapply(seq_along(emi), function(i){
      dtt[,names(emi)[i] := emi[[i]]]
    })
    if(time == "hour"){
      dtt[,time := data.table::hour(data.table::as.ITime(time))][order(time),]
      dtt <- dtt[ , lapply(.SD, sum), .SDcols = !"time", by = "time"]
    }
    if(time == "hour-minute"){
      dtt[,time := paste0(data.table::hour(data.table::as.ITime(time)),":",
                          data.table::minute(data.table::as.ITime(time)))][order(time),]
      dtt <- dtt[ , lapply(.SD, sum), .SDcols = !"time", by = "time"]
    }
    return(dtt)
  }else{
    dtt <- data.table::data.table()
    dtt <- lapply(seq_along(emi), function(i){
      dtt[,names(emi)[i] := emi[[i]]]
    }) %>% data.table::rbindlist()
    return(dtt)
  }
}
