#' @title 
#' Convert estimates from list to data.table format
#' 
#' @description 
#' Read estimates generated by the \code{\link{emis}} or emission factor 
#' functions (e.g. \code{\link{ef_brazil_cetesb}}), , and convert to a data.table format.
#' The function allows one to aggregate emissions or emission factors by time of the day, 
#' vehicle type or road segment (spatial).
#' 
#' @param emi_list List; Emissions list.
#' @param emi_vars Character; Names of 'emi_list' object attributed to emissions or 
#' emission factors. Default is 'emi'.
#' @param veh_vars Character; Names of 'emi_list' object attributed to vehicle
#'  characteristics. Default is 'veh_type'.
#' @param pol_vars Character; Names of 'emi_list' object attributed to pollutants.
#'  Default is 'pollutant'.
#' @param segment_vars Character; Names of 'emi_list' object attributed to the
#' road segments. Default is NULL.
#' 
#' @return data.table.
#' @export
#' 
#' @examples if (interactive()) {
#' library(data.table)
#' library(magrittr)
#' gtfs_file <- system.file("extdata/irl_dub/irl_dub_gtfs.zip", package = "gtfs2emis")
#' gtfs <- gtfstools::read_gtfs(gtfs_file)
#' # Keep single trip
#' gtfs <- gtfstools::filter_by_trip_id(gtfs
#'                                      , trip_id = c('619.3.60-40-d12-1.224.O'
#'                                                    ,"10812.1.60-13-d12-1.26.I"))
#' # Transport model
#'   tp_model <- transport_model(gtfs_data = gtfs,
#'                               spatial_resolution = 100,
#'                               parallel = TRUE)
#' # emission model
#' fleet_df <- read.csv(system.file("extdata/irl_dub/irl_dub_fleet.txt"
#'                                  , package = "gtfs2emis"))
#' 
#' emi_list <- emission_model(tp_model = tp_model
#'                            , ef_model = "ef_europe_emep"
#'                            , fleet_data = fleet_df
#'                            , pollutant = c("CO2","PM10"))
#' # View emission data
#' names(emi_list)
#' emis_to_dt(emi_list
#'            ,veh_vars = c("veh_type","euro","fuel","tech")
#' )
#' emis_to_dt(emi_list
#'            ,veh_vars = c("veh_type","euro","fuel","tech")
#'            ,segment_vars = c("slope","load")
#' )
#' emis_to_dt(emi_list)
#' 
#' emis_to_dt(emi_list
#'            ,emi_vars = "emi"
#'            ,veh_vars = c("veh_type","euro","fuel","tech")
#'            ,pol_vars = "pollutant"
#'            ,segment_vars = c("slope","load")
#' )
#' # View Emission Factor data
#' emis_to_dt(emi_list
#'            ,emi_vars = "EF")
#' emis_to_dt(emi_list
#'            ,emi_vars = "EF"
#'            ,veh_vars = c("veh_type","euro","fuel","tech")
#'            ,segment_vars = c("slope","load"))
#' 
#' # Emission factor model
#' list_ef_br <- ef_brazil_cetesb(pollutant = c("CO","PM10","CO2")
#'                                ,veh_type = c("BUS_URBAN_D","BUS_MICRO_D")
#'                                ,model_year = c(2010,2015)
#'                                ,as_list = TRUE)
#' emis_to_dt(list_ef_br
#'            ,emi_vars = "EF")
#' emis_to_dt(list_ef_br
#'            ,emi_vars = "EF"
#'            ,veh_vars = c("veh_type","model_year"))
#'}
emis_to_dt <- function(emi_list, emi_vars = "emi", veh_vars = "veh_type"
                       , pol_vars = "pollutant", segment_vars = NULL){
  
  #
  # init config
  #
  # 
  # set.seed(1335)
  # dist = units::set_units(rnorm(100,0.250,0.03),"km")
  # ef <- ef_europe(speed = units::set_units(rnorm(100,50,5),"km/h"),
  #                 veh_type = c("Urban Buses Standard 15 - 18 t","Urban Buses Articulated >18 t"),
  #                 euro = c("IV","V"),
  #                 pollutant = c("CO2","NOx"),
  #                 fuel = "Diesel" ,
  #                 tech =  c("SCR","EGR"),
  #                 slope = 0.0,
  #                 load = 0.5,
  #                 fcorr = 1,
  #                 as.list = TRUE)
  # emi_list <- emis(fleet_composition =  c(0.7,0.3),
  #             dist = dist,
  #             ef = ef,
  #             aggregate = FALSE,
  #             as_list = TRUE)
  # 
  # names(emi_list)
  # emi_vars = "emi"
  # veh_vars = c("veh_type","euro","fuel","tech")
  # pol_vars = "pollutant"
  # segment_vars = NULL #c("slope","load")
  # 
  #
  # check list condition -----
  #
  
  if(class(emi_list) != "list"){
    stop("'emi_list' input needs to have a list format.")
  }
  
  # check consistencies----
  lapply(emi_vars, function(i){
    if(!(i %in% names(emi_list))){
      sprintf("emi_vars '%s' argument not found. Please inform a valid 'emi_vars' input."
              ,i)
      stop()
    }
  })
  
  lapply(veh_vars, function(i){
    if(!(i %in% names(emi_list))){
      sprintf("veh_vars '%s' argument not found. Please inform a valid 'veh_vars' input."
              ,i)
      stop()
    }
  })
  
  lapply(pol_vars, function(i){
    if(!(i %in% names(emi_list))){
      sprintf("pol_vars '%s' argument not found. Please inform a valid 'pol_vars' input."
              ,i)
      stop()
    }
  })
  
  lapply(segment_vars, function(i){
    if(!is.null(i)){
      if(!(i %in% names(emi_list))){
        sprintf("segment_vars '%s' argument not found. Please inform a valid 'segment_vars' input."
                ,i)
        stop()
      }
    }
  })
  
  all_vars = c(veh_vars, pol_vars,emi_vars)
  
  
  #
  # check units previously
  #
  
  myunits <- sapply(seq_along(emi_list[[emi_vars]]),function(i){
    units::deparse_unit(emi_list[[emi_vars]][[i]])
  })
  
  if(length(unique(myunits)) == 1){
    myunits <- myunits[1]
  }else{
    message("units are not the same for emissions columns")
    stop()
  }
  
  #
  # merge------
  #
  
  dt <- lapply(1:length(emi_list[[pol_vars]]),function(i){ # i = 1
    
    # add vars
    tmp_dt <- lapply(seq_along(all_vars),function(j){ # j = 1;i = 1
      emi_list[[all_vars[[j]]]][[i]]
    })
    if(!is.null(segment_vars)){
      tmp_dt <- do.call(c, list(tmp_dt, emi_list[segment_vars]))
      tmp_dt <- do.call(cbind,tmp_dt)
      tmp_dt <- data.table::as.data.table(tmp_dt)
      names(tmp_dt) <- c(all_vars,segment_vars)
    }else{
      tmp_dt <- do.call(cbind,tmp_dt)
      tmp_dt <- data.table::as.data.table(tmp_dt)
      names(tmp_dt) <- all_vars
    }
    
    
    # convert columns
    
    tmp_dt[,segment_id := 1:nrow(tmp_dt)]
    if(!is.null(emi_vars))      tmp_dt[,(emi_vars) := lapply(.SD, as.numeric), .SDcols = emi_vars]
    if(!is.null(veh_vars))      tmp_dt[,(veh_vars) := lapply(.SD, as.factor), .SDcols = veh_vars]
    if(!is.null(segment_vars))  tmp_dt[,(segment_vars) := lapply(.SD, as.numeric), .SDcols = segment_vars]
    if(!is.null(pol_vars))      tmp_dt[,(pol_vars) := lapply(.SD, as.character), .SDcols = pol_vars]
    
    return(tmp_dt)
  }) 
  dt <- data.table::rbindlist(dt)
  
  # add units back ----
  
  units(dt[[emi_vars]]) <- myunits
  
  # return
  
  return(dt)
}